services:
  app:
    build: .
    container_name: discord-app
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    command: |
      sh -c "
        # Run migrations if Prisma schema exists
        if [ -f prisma/schema.prisma ]; then npx prisma migrate deploy; fi && \
        node index.js
      "

  postgres:
    image: postgres:17.4
    container_name: discord-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-vodka}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-vodka_pass}
      POSTGRES_DB: ${POSTGRES_DB:-vodka_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8.0-rc1-alpine
    container_name: discord-redis
    restart: unless-stopped
    command: ["redis-server"]

volumes:
  postgres_data:
    driver: local